name: "ShatteredPixels"
highlighter: rouge
markdown: kramdown
permalink: /:year/:month/:title
exclude: [README.md, LICENSE, Makefile]
#baseurl: '/'

# Information for the Atom feed
gereksiz:
   author: "Will"
   email: "astutecat@shatteredpixels.org.uk"