name: "ShatteredPixels"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]
#baseurl: '/'

# Information for the Atom feed
gereksiz:
   author: "Will"
   email: "astutecat@shatteredpixels.org.uk"